/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.Select;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {

    private static final String FIRST_SELECT_EL_ID = "id_sc_field_mercado";
    private static final String SECOND_SELECT_EL_ID = "id_sc_field_datas";
    private static final String SUBMIT_BUTTON = "sc_bbtboletim_bot";
    private static Logger log = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        var chromeOptions = new ChromeOptions();
        chromeOptions.setBinary("/usr/bin/google-chrome-stable");
        chromeOptions.addArguments("--headless"); // Add this line
        chromeOptions.addArguments("--disable-gpu");
        var driver = new ChromeDriver(chromeOptions);
        var page = "http://minas1.ceasa.mg.gov.br/detec/filtro_boletim/filtro_boletim.php";
        log.info("Fetching page: {}", page);
        driver.get(page);
        log.info("Page title: {}", driver.getTitle());
        var first_el = driver.findElement(By.id(FIRST_SELECT_EL_ID));
        log.info("Found a \"{}\" element with the id=\"{}\"", first_el.getTagName(), FIRST_SELECT_EL_ID);
        var first_select = new Select(first_el);
        var options = first_select
                .getOptions()
                .stream()
                // .map(WebElement::getText)
                .map(o -> o.getDomProperty("value"))
                .toList();
        log.info("List of options obtained from the first select element: {}", options);
        first_select.selectByVisibleText("Gov. Valadares - CEARD");
        var second_el = driver.findElement(By.id(SECOND_SELECT_EL_ID));
        log.info("Found a \"{}\" element with the id=\"{}\"", second_el.getTagName(), SECOND_SELECT_EL_ID);
        var secondSelect = new Select(second_el);
        log.info("The list of available dates to select from in the second select element is {}",
                secondSelect.getOptions().size());
        var dateToSelect = "27/12/2024";
        secondSelect.selectByVisibleText(dateToSelect);
        log.info("Selected the value for the second element: \"{}\"", dateToSelect);
        var submitButton = driver.findElement(By.id(SUBMIT_BUTTON));
        log.info("Found a \"{}\" element with the id=\"{}\"", submitButton.getTagName(), SUBMIT_BUTTON);
        submitButton.click();
        log.info("Clicked the submit button");
        log.info("Currently at page \"{}\"", driver.getTitle());
        driver.quit();
    }
}
