services:
  db:
    image: postgres:15
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: denis
      POSTGRES_DB: db
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
